name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.16
    - run: npm install
    - run: npx sass ./sass/style.scss ./build/css/style.css
    - run: ls -lha ./build/css/
     - name: Build
        uses: actions/upload-artifact@v3
        with:
          name: cbuild
          path: ./public    